// ============================================================
// TAGS DE EFICÁCIA
// ============================================================

export const TAG_LABELS = {
  ultra: { label: 'Ultra eficaz', color: 'bg-green-100 text-green-800 border-green-200' },
  eficiente: { label: 'Eficaz', color: 'bg-blue-100 text-blue-700 border-blue-200' },
  complementar: { label: 'Complementar', color: 'bg-amber-100 text-amber-700 border-amber-200' },
};

// ============================================================
// BIBLIOTECA FIXA DE RECEITAS CAPILARES CURADAS (25 receitas)
// ============================================================

export const HAIR_RECIPES = [
  // ── HIDRATAÇÃO ──────────────────────────────────────────
  {
    id: 'babosa-mel',
    name: 'Máscara de Babosa e Mel',
    category: 'Hidratação',
    tag: 'ultra',
    description: 'Hidratação profunda com aloe vera e mel. Fecha cutículas, devolvendo brilho e maciez imediatos.',
    ingredients: ['Babosa (Aloe Vera)', 'Mel'],
    amounts: ['3 colheres de sopa de gel de babosa', '1 colher de sopa de mel puro'],
    instructions: 'Misture bem o gel de babosa com o mel até obter uma mistura homogênea. Aplique nos fios úmidos da raiz às pontas. Deixe agir por 20–30 minutos com touca plástica. Enxágue com água fria.',
    duration_minutes: 30,
    frequency: '2x por semana',
    benefits: ['Hidratação intensa', 'Brilho imediato', 'Fechamento de cutículas', 'Redução do frizz'],
    tips: 'Use mel orgânico para melhores resultados. A touca retém o calor do corpo e potencializa a absorção.',
    hair_types: ['Todos os tipos', 'Especialmente seco e ressecado'],
    problems: ['dry', 'frizz', 'breakage'],
    phase: [1, 2, 3, 4],
  },
  {
    id: 'abacate-azeite',
    name: 'Hidratação com Abacate e Azeite',
    category: 'Hidratação',
    tag: 'ultra',
    description: 'Máscara rica em gorduras boas e vitaminas. Restaura a elasticidade e suaviza fios quebradiços.',
    ingredients: ['Abacate', 'Azeite Extra Virgem'],
    amounts: ['½ abacate maduro', '1 colher de sopa de azeite extra virgem'],
    instructions: 'Amasse o abacate até virar pasta. Misture com o azeite. Aplique nos fios úmidos da raiz às pontas. Cubra com touca plástica. Deixe agir 30–40 minutos. Enxágue bem e lave normalmente.',
    duration_minutes: 40,
    frequency: '1x por semana',
    benefits: ['Elasticidade restaurada', 'Maciez extrema', 'Vitaminas A, D e E', 'Hidratação duradoura'],
    tips: 'Use abacate bem maduro para facilitar a mistura. Retire bem todos os resíduos ao enxaguar.',
    hair_types: ['Ressecados', 'Quebradiços', 'Com frizz'],
    problems: ['dry', 'frizz', 'breakage'],
    phase: [1, 2, 4],
  },
  {
    id: 'banana-mel',
    name: 'Máscara de Banana e Mel',
    category: 'Hidratação',
    tag: 'eficiente',
    description: 'Banana rica em potássio restaura a elasticidade enquanto o mel sela a hidratação nos fios.',
    ingredients: ['Banana', 'Mel'],
    amounts: ['1 banana bem madura', '1 colher de sopa de mel'],
    instructions: 'Amasse ou bata a banana no liquidificador até não ter grumos. Misture com o mel. Aplique nos fios úmidos. Deixe agir 20–25 minutos com touca. Enxágue muito bem removendo todo resíduo de banana.',
    duration_minutes: 25,
    frequency: '1x por semana',
    benefits: ['Elasticidade', 'Hidratação', 'Maciez', 'Nutrição'],
    tips: 'Use banana bem madura (com manchas escuras) — ela dissolve muito melhor e tem mais potássio.',
    hair_types: ['Ressecados', 'Quebradicos', 'Sem elasticidade'],
    problems: ['dry', 'breakage', 'frizz'],
    phase: [1, 2, 4],
  },
  {
    id: 'iogurte-mel',
    name: 'Máscara de Iogurte e Mel',
    category: 'Hidratação',
    tag: 'eficiente',
    description: 'O ácido lático do iogurte suaviza e uniformiza os fios enquanto o mel sela a hidratação.',
    ingredients: ['Iogurte Natural', 'Mel'],
    amounts: ['4 colheres de sopa de iogurte natural integral', '1 colher de sopa de mel'],
    instructions: 'Misture o iogurte com o mel. Aplique nos fios úmidos. Deixe agir por 20 minutos com touca. Enxágue com água morna e finalize com água fria.',
    duration_minutes: 20,
    frequency: '1x por semana',
    benefits: ['Suavização', 'Hidratação', 'Brilho', 'Frizz reduzido'],
    tips: 'Prefira iogurte integral sem sabor. Funciona muito bem como pré-lavagem.',
    hair_types: ['Todos os tipos'],
    problems: ['dry', 'frizz'],
    phase: [1, 4],
  },
  {
    id: 'aloe-limoneno',
    name: 'Babosa com Suco de Limão',
    category: 'Hidratação',
    tag: 'eficiente',
    description: 'Combinação hidratante e purificante. O limão equilibra o pH e a babosa hidrata profundamente.',
    ingredients: ['Babosa (Aloe Vera)', 'Limão'],
    amounts: ['4 colheres de sopa de gel de babosa', '1 colher de chá de suco de limão'],
    instructions: 'Misture o gel de babosa com o suco de limão. Aplique no couro cabeludo e fios úmidos. Massageie suavemente. Deixe agir 20 minutos. Enxágue com água morna.',
    duration_minutes: 20,
    frequency: '1x por semana',
    benefits: ['Hidratação', 'Equilíbrio de pH', 'Limpeza suave', 'Brilho'],
    tips: 'Use o limão em pequena quantidade — o excesso pode ressecar. Evite exposição ao sol após aplicação.',
    hair_types: ['Oleosos', 'Com caspa leve', 'Normais'],
    problems: ['dry', 'frizz'],
    phase: [1, 4],
  },
  {
    id: 'mel-azeite',
    name: 'Máscara de Mel e Azeite',
    category: 'Hidratação',
    tag: 'ultra',
    description: 'Dupla clássica de hidratação e nutrição. Mel retém água nos fios e azeite sela e protege a fibra capilar.',
    ingredients: ['Mel', 'Azeite Extra Virgem'],
    amounts: ['2 colheres de sopa de mel', '1 colher de sopa de azeite extra virgem'],
    instructions: 'Misture bem o mel com o azeite. Aplique nos fios úmidos da raiz às pontas. Cubra com touca plástica. Deixe agir 30 minutos. Enxágue com água morna e lave com shampoo suave.',
    duration_minutes: 30,
    frequency: '2x por semana',
    benefits: ['Hidratação profunda', 'Nutrição', 'Maciez', 'Brilho'],
    tips: 'Aqueça levemente a mistura antes de aplicar — potencializa a absorção.',
    hair_types: ['Todos os tipos', 'Especialmente secos'],
    problems: ['dry', 'frizz', 'breakage'],
    phase: [1, 2, 4],
  },

  // ── NUTRIÇÃO ────────────────────────────────────────────
  {
    id: 'oleo-coco-nutricao',
    name: 'Nutrição com Óleo de Coco Puro',
    category: 'Nutrição',
    tag: 'ultra',
    description: 'Nutrição profunda para fios ressecados. O óleo de coco penetra no córtex e fortalece a estrutura do fio.',
    ingredients: ['Óleo de Coco'],
    amounts: ['2–3 colheres de sopa de óleo de coco extravirgem'],
    instructions: 'Aqueça levemente o óleo nas mãos. Aplique nos fios secos do meio às pontas, evitando a raiz. Deixe agir por 1–2 horas (ou de um dia para o outro). Lave com shampoo suave duas vezes.',
    duration_minutes: 60,
    frequency: '1x por semana',
    benefits: ['Nutrição profunda', 'Fortalecimento', 'Redução de quebra', 'Brilho intenso'],
    tips: 'Se o cabelo for fino, aplique apenas nas pontas. Usar de noite e lavar de manhã potencializa o resultado.',
    hair_types: ['Secos', 'Danificados', 'Grossos'],
    problems: ['dry', 'breakage', 'frizz'],
    phase: [1, 2, 3, 4],
  },
  {
    id: 'abacate-coco',
    name: 'Nutrição com Abacate e Óleo de Coco',
    category: 'Nutrição',
    tag: 'ultra',
    description: 'Máscara nutritiva de alto impacto. Combina ácidos graxos do coco com vitaminas do abacate para fios visivelmente mais fortes.',
    ingredients: ['Abacate', 'Óleo de Coco'],
    amounts: ['½ abacate maduro', '1 colher de sopa de óleo de coco'],
    instructions: 'Amasse o abacate e misture com o óleo de coco (amolecido). Aplique nos fios úmidos. Deixe agir 30–40 minutos com touca. Enxágue bem e lave normalmente.',
    duration_minutes: 40,
    frequency: '1x por semana',
    benefits: ['Nutrição intensa', 'Fortalecimento', 'Maciez', 'Brilho intenso'],
    tips: 'Esta é uma das máscaras mais nutritivas da biblioteca. Ideal para cabelos muito secos ou danificados por química.',
    hair_types: ['Secos', 'Danificados', 'Grossos'],
    problems: ['dry', 'breakage'],
    phase: [2, 3, 4],
  },
  {
    id: 'banana-coco',
    name: 'Máscara de Banana e Óleo de Coco',
    category: 'Nutrição',
    tag: 'eficiente',
    description: 'Banana rica em potássio e vitaminas fortalece o fio. O óleo de coco sela e dá brilho.',
    ingredients: ['Banana', 'Óleo de Coco'],
    amounts: ['1 banana bem madura', '1 colher de sopa de óleo de coco'],
    instructions: 'Amasse a banana até virar pasta bem lisinha (sem grumos). Misture com o óleo de coco. Aplique nos fios úmidos. Deixe agir 20 minutos com touca. Enxágue muito bem — retire todos os resíduos de banana.',
    duration_minutes: 25,
    frequency: '1x por semana',
    benefits: ['Nutrição', 'Fortalecimento', 'Maciez', 'Brilho'],
    tips: 'Use banana bem madura (com manchas pretas) para facilitar dissolver. Liquidificar ajuda a evitar grumos.',
    hair_types: ['Ressecados', 'Quebradiços'],
    problems: ['dry', 'breakage'],
    phase: [1, 2, 4],
  },

  // ── RECONSTRUÇÃO ────────────────────────────────────────
  {
    id: 'ovo-mel',
    name: 'Reconstrução com Ovo e Mel',
    category: 'Reconstrução',
    tag: 'eficiente',
    description: 'Combinação de proteína do ovo com hidratação do mel. Ideal para fios fragilizados por química ou calor.',
    ingredients: ['Ovo', 'Mel'],
    amounts: ['1 ovo inteiro', '1 colher de sopa de mel'],
    instructions: 'Bata o ovo e misture com o mel. Aplique nos fios úmidos. Deixe agir por 15–20 minutos. Enxágue com água FRIA (água quente cozinha o ovo nos fios). Lave com shampoo suave.',
    duration_minutes: 20,
    frequency: '1x por semana',
    benefits: ['Aporte proteico', 'Fortalecimento', 'Redução de quebra', 'Nutrição'],
    tips: 'IMPORTANTE: use sempre água fria para enxaguar, nunca quente. Misture bem para evitar grumos.',
    hair_types: ['Fragilizados', 'Com quebra', 'Após química'],
    problems: ['breakage', 'hair_loss', 'no_growth'],
    phase: [2, 3],
  },
  {
    id: 'iogurte-ovo',
    name: 'Reconstrução com Iogurte e Ovo',
    category: 'Reconstrução',
    tag: 'eficiente',
    description: 'Máscara proteica dupla que reconstrói os fios danificados. O ácido lático do iogurte potencializa a absorção proteica.',
    ingredients: ['Iogurte Natural', 'Ovo'],
    amounts: ['3 colheres de sopa de iogurte natural integral', '1 ovo (só a gema)'],
    instructions: 'Misture o iogurte com a gema de ovo. Aplique nos fios úmidos do meio às pontas. Deixe agir 20–25 minutos com touca. Enxágue OBRIGATORIAMENTE com água fria. Lave com shampoo suave.',
    duration_minutes: 25,
    frequency: '1x por semana',
    benefits: ['Reconstrução proteica', 'Redução de quebra', 'Fortalecimento', 'Maciez'],
    tips: 'Use apenas a gema — ela tem mais nutrientes e menos risco de resíduo. Água fria é obrigatória.',
    hair_types: ['Fragilizados', 'Porosos', 'Com química'],
    problems: ['breakage', 'hair_loss'],
    phase: [2, 3],
  },
  {
    id: 'iogurte-mel-reconstrucao',
    name: 'Máscara Proteica de Iogurte e Mel',
    category: 'Reconstrução',
    tag: 'eficiente',
    description: 'Reconstrução leve com proteínas do iogurte e propriedades selantes do mel. Perfeita para fios com quebra moderada.',
    ingredients: ['Iogurte Natural', 'Mel'],
    amounts: ['5 colheres de sopa de iogurte grego', '1 colher de sopa de mel'],
    instructions: 'Misture bem o iogurte grego com o mel. Aplique do couro cabeludo até as pontas. Deixe agir 25 minutos com touca. Enxágue com água fria e lave normalmente.',
    duration_minutes: 25,
    frequency: '1–2x por semana',
    benefits: ['Proteínas', 'Redução de quebra', 'Hidratação', 'Brilho'],
    tips: 'O iogurte grego tem mais proteínas que o normal. Ótimo para quem está na fase de reconstrução.',
    hair_types: ['Com quebra', 'Fragilizados'],
    problems: ['breakage', 'dry'],
    phase: [2, 3, 4],
  },

  // ── SELANTE ─────────────────────────────────────────────
  {
    id: 'vinagre-maca',
    name: 'Selante com Vinagre de Maçã',
    category: 'Selante',
    tag: 'complementar',
    description: 'Rinse final que fecha as cutículas e equilibra o pH. Resultado: brilho espelhado e frizz reduzido.',
    ingredients: ['Vinagre de Maçã'],
    amounts: ['2 colheres de sopa de vinagre de maçã', '1 copo de água fria'],
    instructions: 'Misture o vinagre de maçã na água. Após lavar e condicionar normalmente, despeje a mistura nos fios. Massageie suavemente por 1–2 minutos. Não enxágue — o cheiro desaparece quando o cabelo seca.',
    duration_minutes: 5,
    frequency: '1x por semana',
    benefits: ['Fechamento de cutículas', 'Brilho intenso', 'Anti-frizz', 'pH equilibrado'],
    tips: 'Use sempre como etapa final, depois do condicionador. O cheiro de vinagre some completamente após secar.',
    hair_types: ['Todos os tipos'],
    problems: ['frizz', 'dry'],
    phase: [1, 2, 3, 4],
  },

  // ── COURO CABELUDO ──────────────────────────────────────
  {
    id: 'cafe-estimulo',
    name: 'Esfoliante de Café para o Couro Cabeludo',
    category: 'Couro Cabeludo',
    tag: 'complementar',
    description: 'Cafeína estimula o folículo, remove resíduos do couro cabeludo e prepara para melhor absorção.',
    ingredients: ['Café', 'Azeite Extra Virgem'],
    amounts: ['3 colheres de sopa de café em pó (usado ou fresco)', '1 colher de chá de azeite ou óleo de coco'],
    instructions: 'Misture o café com o óleo. Aplique no couro cabeludo úmido com movimentos circulares. Massageie por 3–5 minutos. Deixe agir por 10 minutos. Enxágue e lave normalmente.',
    duration_minutes: 20,
    frequency: '1x por semana',
    benefits: ['Estimula folículos', 'Esfoliação do couro cabeludo', 'Melhora circulação', 'Remove resíduos'],
    tips: 'O café usado do dia a dia funciona perfeitamente. Faça com o cabelo molhado para facilitar a aplicação.',
    hair_types: ['Com queda', 'Couro cabeludo ressecado', 'Crescimento lento'],
    problems: ['hair_loss', 'no_growth'],
    phase: [3, 4],
  },
  {
    id: 'cebola-crescimento',
    name: 'Tônico de Cebola para Crescimento',
    category: 'Couro Cabeludo',
    tag: 'complementar',
    description: 'Rico em enxofre, estimula a circulação no couro cabeludo e reduz a queda com uso consistente.',
    ingredients: ['Cebola'],
    amounts: ['2 cebolas médias'],
    instructions: 'Processe ou rale as cebolas e coe o suco. Aplique diretamente no couro cabeludo com algodão ou borrifador. Massageie por 5 minutos. Deixe agir por 30–60 minutos. Lave bem o cabelo.',
    duration_minutes: 45,
    frequency: '2–3x por semana',
    benefits: ['Estimula crescimento', 'Reduz queda', 'Fortalece raízes', 'Circulação no couro cabeludo'],
    tips: 'O cheiro some completamente após lavar bem. Use por pelo menos 4 semanas para ver resultados.',
    hair_types: ['Com queda', 'Crescimento lento'],
    problems: ['hair_loss', 'no_growth'],
    phase: [3, 4],
  },
  {
    id: 'cebola-coco',
    name: 'Tônico de Cebola com Óleo de Coco',
    category: 'Couro Cabeludo',
    tag: 'complementar',
    description: 'Versão potencializada do tônico de cebola. O óleo de coco sela o tratamento e reduz o cheiro característico.',
    ingredients: ['Cebola', 'Óleo de Coco'],
    amounts: ['1 cebola média', '1 colher de sopa de óleo de coco'],
    instructions: 'Extraia o suco da cebola e misture com o óleo de coco levemente aquecido. Aplique no couro cabeludo. Massageie por 5 minutos. Deixe agir 30 minutos com touca. Lave com shampoo duas vezes.',
    duration_minutes: 40,
    frequency: '2x por semana',
    benefits: ['Estimula crescimento', 'Reduz queda', 'Nutre couro cabeludo', 'Fortalece raízes'],
    tips: 'O óleo de coco ameniza o odor da cebola e ainda nutre o couro cabeludo enquanto o tônico age.',
    hair_types: ['Com queda', 'Crescimento lento', 'Couro seco'],
    problems: ['hair_loss', 'no_growth'],
    phase: [3, 4],
  },
  {
    id: 'cha-verde-crescimento',
    name: 'Tônico de Chá Verde',
    category: 'Couro Cabeludo',
    tag: 'complementar',
    description: 'Antioxidantes do chá verde combatem inflamação no couro cabeludo, reduzem queda e estimulam crescimento.',
    ingredients: ['Chá Verde'],
    amounts: ['2 saquinhos de chá verde', '250ml de água quente'],
    instructions: 'Prepare um chá verde concentrado e deixe esfriar completamente. Aplique no couro cabeludo com borrifador ou algodão. Massageie suavemente por 3 minutos. Deixe agir 30 minutos. Lave normalmente.',
    duration_minutes: 35,
    frequency: '3x por semana',
    benefits: ['Antioxidante', 'Reduz queda', 'Estimula crescimento', 'Anti-inflamatório'],
    tips: 'Use após esfriar completamente. Prepare em quantidade e guarde na geladeira por até 3 dias.',
    hair_types: ['Com queda', 'Couro cabeludo inflamado'],
    problems: ['hair_loss', 'no_growth'],
    phase: [3, 4],
  },

  // ── CRESCIMENTO ─────────────────────────────────────────
  {
    id: 'babosa-cebola',
    name: 'Máscara de Babosa com Cebola',
    category: 'Crescimento',
    tag: 'eficiente',
    description: 'Combinação poderosa para crescimento. A babosa hidrata e a cebola estimula os folículos diretamente.',
    ingredients: ['Babosa (Aloe Vera)', 'Cebola'],
    amounts: ['3 colheres de sopa de gel de babosa', '1 colher de sopa de suco de cebola'],
    instructions: 'Extraia o suco da cebola e misture com o gel de babosa. Aplique no couro cabeludo e nos fios. Massageie por 5 minutos. Deixe agir 30 minutos com touca. Lave bem com shampoo.',
    duration_minutes: 40,
    frequency: '2x por semana',
    benefits: ['Estimula crescimento', 'Hidratação', 'Reduz queda', 'Fortalece raízes'],
    tips: 'A babosa neutraliza parcialmente o odor da cebola. Se o cheiro for forte, adicione uma gota de óleo essencial de lavanda.',
    hair_types: ['Com queda', 'Crescimento lento'],
    problems: ['hair_loss', 'no_growth'],
    phase: [3],
  },
  {
    id: 'mel-coco-crescimento',
    name: 'Máscara Nutritiva de Mel e Coco para Crescimento',
    category: 'Crescimento',
    tag: 'eficiente',
    description: 'Nutre o couro cabeludo e os fios simultaneamente, criando o ambiente ideal para o crescimento saudável.',
    ingredients: ['Mel', 'Óleo de Coco'],
    amounts: ['2 colheres de sopa de mel', '2 colheres de sopa de óleo de coco'],
    instructions: 'Misture o mel com o óleo de coco aquecido. Aplique com massagem no couro cabeludo por 5 minutos. Espalhe pelo restante dos fios. Deixe agir 30–40 minutos com touca. Lave com shampoo duas vezes.',
    duration_minutes: 45,
    frequency: '1x por semana',
    benefits: ['Estimula crescimento', 'Nutre raízes', 'Hidratação profunda', 'Fortalecimento'],
    tips: 'A massagem no couro cabeludo é essencial — ela ativa a circulação e potencializa o efeito do tratamento.',
    hair_types: ['Todos os tipos', 'Com crescimento lento'],
    problems: ['no_growth', 'hair_loss', 'dry'],
    phase: [3, 4],
  },

  // ── MANUTENÇÃO ──────────────────────────────────────────
  {
    id: 'babosa-pura',
    name: 'Ativador de Cachos com Babosa Pura',
    category: 'Manutenção',
    tag: 'ultra',
    description: 'Gel natural de babosa pura para definição e hidratação diária sem pesar nos fios.',
    ingredients: ['Babosa (Aloe Vera)'],
    amounts: ['2–3 colheres de sopa de gel de babosa fresco'],
    instructions: 'Aplique o gel de babosa nos fios úmidos após lavar. Modele os cachos ou espalhe pelos fios lisos. Não enxágue. Deixe secar naturalmente ou com difusor.',
    duration_minutes: 5,
    frequency: 'Diário ou conforme necessário',
    benefits: ['Hidratação leve', 'Definição', 'Brilho', 'Anti-frizz suave'],
    tips: 'Extraia o gel diretamente da folha de babosa para resultado mais fresco e eficaz.',
    hair_types: ['Cacheados', 'Ondulados', 'Todos os tipos'],
    problems: ['frizz', 'dry'],
    phase: [4],
  },
  {
    id: 'oleo-argan-finalizacao',
    name: 'Finalização com Óleo de Coco nas Pontas',
    category: 'Manutenção',
    tag: 'complementar',
    description: 'Aplicação leve de óleo de coco nas pontas para selar hidratação e evitar quebra no dia a dia.',
    ingredients: ['Óleo de Coco'],
    amounts: ['2–3 gotas de óleo de coco nas palmas das mãos'],
    instructions: 'Esfregue as gotas de óleo entre as palmas. Aplique somente nas pontas do cabelo seco ou úmido. Não aplique na raiz. Use como finalizador diário.',
    duration_minutes: 2,
    frequency: 'Diário (conforme necessário)',
    benefits: ['Proteção das pontas', 'Redução de quebra', 'Brilho', 'Selagem'],
    tips: 'Menos é mais — excesso de óleo pesa no cabelo. Comece com 2 gotas e ajuste conforme necessidade.',
    hair_types: ['Todos os tipos'],
    problems: ['breakage', 'dry'],
    phase: [4],
  },
  {
    id: 'mascara-manutencao',
    name: 'Máscara de Manutenção Semanal',
    category: 'Manutenção',
    tag: 'eficiente',
    description: 'Máscara leve de manutenção para preservar os resultados conquistados. Mantém hidratação e brilho semana a semana.',
    ingredients: ['Mel', 'Iogurte Natural'],
    amounts: ['1 colher de sopa de mel', '3 colheres de sopa de iogurte natural'],
    instructions: 'Misture o mel com o iogurte. Aplique nos fios úmidos após lavar. Deixe agir 15–20 minutos. Enxágue bem com água morna.',
    duration_minutes: 20,
    frequency: '1x por semana',
    benefits: ['Manutenção da hidratação', 'Brilho', 'Maciez', 'Fácil de preparar'],
    tips: 'Essa é sua receita de manutenção — simples, rápida e eficaz para manter os resultados conquistados.',
    hair_types: ['Todos os tipos'],
    problems: ['dry', 'frizz'],
    phase: [4],
  },

  // ── EXTRA ────────────────────────────────────────────────
  {
    id: 'mel-puro-pontas',
    name: 'Hidratação com Mel Puro nas Pontas',
    category: 'Hidratação',
    tag: 'ultra',
    description: 'Aplicação concentrada de mel nas pontas mais ressecadas. Rápido, simples e muito eficaz.',
    ingredients: ['Mel'],
    amounts: ['1 colher de chá de mel puro'],
    instructions: 'Aplique o mel diretamente nas pontas do cabelo úmido. Deixe agir 10–15 minutos. Enxágue com água fria. Lave normalmente. Foque apenas nas pontas — evite raiz.',
    duration_minutes: 15,
    frequency: '2–3x por semana',
    benefits: ['Hidratação focada nas pontas', 'Redução de dupla pontagem', 'Brilho', 'Rápido e eficaz'],
    tips: 'Ótimo para fazer antes do banho enquanto você espera a temperatura da água. Simples e altamente eficaz.',
    hair_types: ['Com pontas danificadas', 'Todos os tipos'],
    problems: ['breakage', 'dry'],
    phase: [1, 2, 4],
  },

  // ── MÉTODO ESSENCIAL ─────────────────────────────────────
  {
    id: 'tratamento-noturno-oleo',
    name: 'Tratamento Noturno de Óleo',
    category: 'Nutrição',
    tag: 'ultra',
    description: 'Tratamento profundo feito durante a noite. Os óleos penetram nos fios enquanto você dorme, potencializando a nutrição e recuperação capilar.',
    ingredients: ['Óleo de Coco', 'Óleo de Rícino', 'Alecrim'],
    amounts: ['1 dedo de óleo de coco', '1 dedo de óleo de rícino', '7 gotas de alecrim'],
    instructions: 'Em um recipiente pequeno (uma garrafinha ou potinho), coloque 1 dedo de óleo de coco e 1 dedo de óleo de rícino — a medida "dedo" é a altura do líquido dentro do recipiente, não na mão. Acrescente as 7 gotas de alecrim e misture agitando bem. Aplique no cabelo sujo (sem lavar antes), massageando o couro cabeludo e distribuindo pelo comprimento dos fios. Cubra com touca descartável e durma com o produto. Lave normalmente no dia seguinte com shampoo, repetindo a lavagem 2 vezes para remover todo o óleo.',
    duration_minutes: 480,
    frequency: '1x por semana',
    benefits: ['Nutrição profunda noturna', 'Estímulo ao crescimento', 'Fortalecimento', 'Hidratação intensa'],
    tips: 'Coloque uma touca descartável para não sujar o travesseiro. Lave bem com shampoo duas vezes no dia seguinte.',
    hair_types: ['Todos os tipos'],
    problems: ['dry', 'breakage', 'hair_loss', 'no_growth'],
    phase: [1, 2, 3, 4],
  },
  {
    id: 'maizena-acucar',
    name: 'Máscara de Maizena + Açúcar',
    category: 'Hidratação',
    tag: 'eficiente',
    description: 'Máscara selante e hidratante com amido de milho e açúcar. Deixa os fios macios, com brilho e sem frizz.',
    ingredients: ['Creme capilar', 'Amido de milho (maizena)', 'Açúcar', 'Limão ou Vinagre de Maçã'],
    amounts: ['2 colheres de creme ou máscara capilar', '2 colheres de amido de milho (maizena)', '2 colheres de açúcar', 'Limão ou vinagre de maçã a gosto'],
    instructions: 'Em um recipiente, misture o creme capilar, a maizena e o açúcar até formar uma pasta homogênea. Adicione algumas gotas de limão ou vinagre de maçã a gosto e misture novamente. Aplique nos fios após lavar o cabelo com shampoo, distribuindo do comprimento até as pontas. Deixe agir por 40 minutos com touca plástica. Enxágue bem com água fria.',
    duration_minutes: 40,
    frequency: '1x por semana',
    benefits: ['Maciez intensa', 'Brilho', 'Selamento das cutículas', 'Controle do frizz'],
    tips: 'Use após lavar o cabelo com shampoo. O açúcar e o ácido do limão ajudam a abrir a cutícula para melhor absorção.',
    hair_types: ['Todos os tipos'],
    problems: ['dry', 'frizz', 'breakage'],
    phase: [1, 2, 3, 4],
  },
];

// ============================================================
// INGREDIENTES COM TAGS DE EFICÁCIA
// ============================================================

// 8 ingredientes curados — obrigatórios + complementares por problema
export const HAIR_INGREDIENTS = [
  { name: 'Babosa (Aloe Vera)', emoji: '🪴', tag: 'ultra', benefits: ['Hidratação', 'Crescimento', 'Anti-queda'] },
  { name: 'Mel', emoji: '🍯', tag: 'ultra', benefits: ['Nutrição', 'Brilho', 'Hidratação'] },
  { name: 'Óleo de Coco', emoji: '🥥', tag: 'eficiente', benefits: ['Nutrição profunda', 'Proteção', 'Brilho'] },
  { name: 'Abacate', emoji: '🥑', tag: 'eficiente', benefits: ['Hidratação intensa', 'Nutrição', 'Maciez'] },
  { name: 'Ovo', emoji: '🥚', tag: 'eficiente', benefits: ['Proteína', 'Fortalecimento', 'Reduz quebra'] },
  { name: 'Vinagre de Maçã', emoji: '🍎', tag: 'complementar', benefits: ['Fecha cutícula', 'Brilho', 'Anti-frizz'] },
  { name: 'Café', emoji: '☕', tag: 'complementar', benefits: ['Estimula crescimento', 'Circulação', 'Anti-queda'] },
  { name: 'Cebola', emoji: '🧅', tag: 'complementar', benefits: ['Anti-queda', 'Crescimento', 'Couro cabeludo'] },
];

// ============================================================
// SISTEMA DE FASES — JORNADA CAPILAR CONTÍNUA
// ============================================================

export const HAIR_PHASES = [
  {
    id: 1,
    name: 'Recuperação',
    duration_days: 21,
    focus: 'Hidratar profundamente e reparar os danos existentes',
    emoji: '🌱',
    color: 'emerald',
    description: 'O primeiro passo é restaurar o que foi perdido. Vamos hidratar, fechar cutículas e criar hábitos que param o dano.',
    goals: ['Hidratação profunda', 'Fechamento de cutículas', 'Redução do frizz', 'Eliminar hábitos prejudiciais'],
  },
  {
    id: 2,
    name: 'Fortalecimento',
    duration_days: 21,
    focus: 'Reduzir quebra e melhorar a estrutura do fio',
    emoji: '💪',
    color: 'blue',
    description: 'Com a hidratação restabelecida, é hora de fortalecer a fibra capilar e reduzir a quebra sistematicamente.',
    goals: ['Aporte proteico', 'Redução de quebra', 'Fortalecimento da fibra', 'Elasticidade restaurada'],
  },
  {
    id: 3,
    name: 'Crescimento',
    duration_days: 21,
    focus: 'Estimular o crescimento saudável e reduzir a queda',
    emoji: '🚀',
    color: 'violet',
    description: 'Couro cabeludo saudável cresce mais. Nesta fase focamos em nutrição da raiz e estímulo dos folículos.',
    goals: ['Estimular folículos', 'Reduzir queda', 'Nutrição da raiz', 'Crescimento acelerado'],
  },
  {
    id: 4,
    name: 'Manutenção',
    duration_days: null,
    focus: 'Manter os resultados e prevenir novos danos',
    emoji: '✨',
    color: 'amber',
    description: 'Você chegou ao estado ideal. Agora é manter com consistência e seguir evoluindo mês a mês.',
    goals: ['Manter hidratação', 'Prevenir danos', 'Consistência nos hábitos', 'Evolução contínua'],
  },
];

// ============================================================
// PLANOS POR FASE (21 dias cada)
// ============================================================

export const PHASE_PLANS = {
  // FASE 1 — RECUPERAÇÃO
  1: [
    { day: 1,  type: 'habit',     task: 'Lave com água morna (nunca quente)', icon: 'droplets' },
    { day: 2,  type: 'habit',     task: 'Evite prender o cabelo molhado', icon: 'droplets' },
    { day: 3,  type: 'treatment', task: 'Hidratação profunda por 20–30 min', icon: 'sparkles', recipe_options: ['babosa-mel', 'mel-azeite'] },
    { day: 4,  type: 'habit',     task: 'Beba pelo menos 2L de água hoje', icon: 'droplets' },
    { day: 5,  type: 'rest',      task: 'Dia de descanso — mantenha apenas os hábitos essenciais', icon: 'leaf' },
    { day: 6,  type: 'treatment', task: 'Nutrição capilar por 1 hora', icon: 'sparkles', recipe_options: ['oleo-coco-nutricao', 'banana-coco'] },
    { day: 7,  type: 'checkin',   task: 'Check-in: observe o brilho e toque os fios. Tire uma foto!', icon: 'camera' },
    { day: 8,  type: 'habit',     task: 'Finalize o banho com água fria por 30 segundos', icon: 'droplets' },
    { day: 9,  type: 'treatment', task: 'Hidratação profunda por 20–30 min', icon: 'sparkles', recipe_options: ['babosa-mel', 'abacate-azeite'] },
    { day: 10, type: 'habit',     task: 'Evite o secador hoje — deixe secar naturalmente', icon: 'droplets' },
    { day: 11, type: 'treatment', task: 'Selagem dos fios após lavagem', icon: 'sparkles', recipe_options: ['vinagre-maca', 'babosa-pura'] },
    { day: 12, type: 'rest',      task: 'Dia de descanso — reforce os hábitos', icon: 'leaf' },
    { day: 13, type: 'habit',     task: 'Beba 2L de água e evite água quente no banho', icon: 'droplets' },
    { day: 14, type: 'checkin',   task: 'Check-in de 2 semanas: compare com a primeira. Há melhora?', icon: 'camera' },
    { day: 15, type: 'treatment', task: 'Hidratação profunda por 30–40 min', icon: 'sparkles', recipe_options: ['abacate-azeite', 'banana-mel'] },
    { day: 16, type: 'habit',     task: 'Durma com o cabelo solto num travesseiro limpo', icon: 'droplets' },
    { day: 17, type: 'treatment', task: 'Hidratação profunda por 20–30 min', icon: 'sparkles', recipe_options: ['babosa-mel', 'iogurte-mel'] },
    { day: 18, type: 'rest',      task: 'Dia de descanso — reforce os hábitos aprendidos', icon: 'leaf' },
    { day: 19, type: 'treatment', task: 'Nutrição capilar por 1 hora', icon: 'sparkles', recipe_options: ['oleo-coco-nutricao', 'mel-azeite'] },
    { day: 20, type: 'habit',     task: 'Evite secador, chapinha e elásticos com metal', icon: 'droplets' },
    { day: 21, type: 'checkin',   task: 'Check-in final da Fase 1: compare o antes e depois! 🎉', icon: 'camera' },
  ],

  // FASE 2 — FORTALECIMENTO
  2: [
    { day: 1,  type: 'habit',     task: 'Mantenha os hábitos da fase anterior como base', icon: 'droplets' },
    { day: 2,  type: 'treatment', task: 'Reconstrução proteica por 20–25 min', icon: 'sparkles', recipe_options: ['ovo-mel', 'iogurte-mel-reconstrucao'] },
    { day: 3,  type: 'habit',     task: 'Corte as pontas duplas — favorece o crescimento', icon: 'droplets' },
    { day: 4,  type: 'rest',      task: 'Dia de descanso — reforce hábitos de hidratação', icon: 'leaf' },
    { day: 5,  type: 'treatment', task: 'Nutrição capilar intensa por 40 min', icon: 'sparkles', recipe_options: ['abacate-coco', 'oleo-coco-nutricao'] },
    { day: 6,  type: 'habit',     task: 'Evite elásticos que puxam o cabelo', icon: 'droplets' },
    { day: 7,  type: 'checkin',   task: 'Check-in semana 1 da Fase 2: observe a quebra diminuindo', icon: 'camera' },
    { day: 8,  type: 'treatment', task: 'Reconstrução proteica por 20–25 min', icon: 'sparkles', recipe_options: ['iogurte-ovo', 'ovo-mel'] },
    { day: 9,  type: 'habit',     task: 'Beba 2L de água e evite água muito quente', icon: 'droplets' },
    { day: 10, type: 'treatment', task: 'Selagem dos fios após lavagem', icon: 'sparkles', recipe_options: ['vinagre-maca', 'oleo-argan-finalizacao'] },
    { day: 11, type: 'rest',      task: 'Dia de descanso', icon: 'leaf' },
    { day: 12, type: 'treatment', task: 'Hidratação profunda por 20–25 min', icon: 'sparkles', recipe_options: ['banana-mel', 'babosa-mel'] },
    { day: 13, type: 'habit',     task: 'Evite calor hoje — sem secador ou chapinha', icon: 'droplets' },
    { day: 14, type: 'checkin',   task: 'Check-in de 2 semanas: compare a quebra', icon: 'camera' },
    { day: 15, type: 'treatment', task: 'Reconstrução proteica por 20–25 min', icon: 'sparkles', recipe_options: ['ovo-mel', 'iogurte-ovo'] },
    { day: 16, type: 'habit',     task: 'Durma com trança solta para reduzir quebra noturna', icon: 'droplets' },
    { day: 17, type: 'treatment', task: 'Hidratação profunda por 30–40 min', icon: 'sparkles', recipe_options: ['abacate-azeite', 'mel-azeite'] },
    { day: 18, type: 'rest',      task: 'Dia de descanso', icon: 'leaf' },
    { day: 19, type: 'treatment', task: 'Reconstrução proteica por 20–25 min', icon: 'sparkles', recipe_options: ['iogurte-mel-reconstrucao', 'banana-coco'] },
    { day: 20, type: 'habit',     task: 'Aplique óleo de coco nas pontas antes de dormir', icon: 'droplets' },
    { day: 21, type: 'checkin',   task: 'Check-in final da Fase 2: celebre a redução de quebra! 💪', icon: 'camera' },
  ],

  // FASE 3 — CRESCIMENTO
  3: [
    { day: 1,  type: 'habit',     task: 'Massageie o couro cabeludo por 5 min hoje', icon: 'droplets' },
    { day: 2,  type: 'treatment', task: 'Esfoliação do couro cabeludo por 20 min', icon: 'sparkles', recipe_options: ['cafe-estimulo', 'babosa-cebola'] },
    { day: 3,  type: 'habit',     task: 'Mantenha hidratação: beba 2L de água', icon: 'droplets' },
    { day: 4,  type: 'treatment', task: 'Tônico estimulante para crescimento por 40 min', icon: 'sparkles', recipe_options: ['cebola-coco', 'mel-coco-crescimento'] },
    { day: 5,  type: 'rest',      task: 'Dia de descanso — mantenha os hábitos', icon: 'leaf' },
    { day: 6,  type: 'treatment', task: 'Tônico anti-queda por 30–35 min', icon: 'sparkles', recipe_options: ['cha-verde-crescimento', 'cebola-crescimento'] },
    { day: 7,  type: 'checkin',   task: 'Check-in semana 1 da Fase 3: observe o couro cabeludo', icon: 'camera' },
    { day: 8,  type: 'treatment', task: 'Tratamento de raiz e comprimento por 40 min', icon: 'sparkles', recipe_options: ['babosa-cebola', 'mel-coco-crescimento'] },
    { day: 9,  type: 'habit',     task: 'Massageie o couro cabeludo por 5 min antes de dormir', icon: 'droplets' },
    { day: 10, type: 'treatment', task: 'Esfoliação do couro cabeludo por 20 min', icon: 'sparkles', recipe_options: ['cafe-estimulo', 'cebola-coco'] },
    { day: 11, type: 'rest',      task: 'Dia de descanso', icon: 'leaf' },
    { day: 12, type: 'treatment', task: 'Tônico estimulante para crescimento por 40–45 min', icon: 'sparkles', recipe_options: ['cebola-crescimento', 'babosa-cebola'] },
    { day: 13, type: 'habit',     task: 'Evite prender o cabelo com tensão — favorece a queda', icon: 'droplets' },
    { day: 14, type: 'checkin',   task: 'Check-in de 2 semanas: a queda diminuiu?', icon: 'camera' },
    { day: 15, type: 'treatment', task: 'Nutrição de raiz para crescimento por 40–45 min', icon: 'sparkles', recipe_options: ['mel-coco-crescimento', 'abacate-coco'] },
    { day: 16, type: 'habit',     task: 'Massageie o couro cabeludo com as pontas dos dedos por 5 min', icon: 'droplets' },
    { day: 17, type: 'treatment', task: 'Tônico anti-queda por 30–35 min', icon: 'sparkles', recipe_options: ['cha-verde-crescimento', 'cebola-coco'] },
    { day: 18, type: 'rest',      task: 'Dia de descanso', icon: 'leaf' },
    { day: 19, type: 'treatment', task: 'Tratamento de raiz e comprimento por 40 min', icon: 'sparkles', recipe_options: ['babosa-cebola', 'mel-coco-crescimento'] },
    { day: 20, type: 'habit',     task: 'Beba 2L de água e faça massagem capilar antes de dormir', icon: 'droplets' },
    { day: 21, type: 'checkin',   task: 'Check-in final da Fase 3: seu cabelo cresceu! 🚀', icon: 'camera' },
  ],

  // FASE 4 — MANUTENÇÃO (plano rolante de 21 dias)
  4: [
    { day: 1,  type: 'habit',     task: 'Aplique babosa pura nos fios como hidratante leve', icon: 'droplets' },
    { day: 2,  type: 'habit',     task: 'Mantenha água fria no final do banho', icon: 'droplets' },
    { day: 3,  type: 'treatment', task: 'Hidratação de manutenção por 20 min', icon: 'sparkles', recipe_options: ['mascara-manutencao', 'iogurte-mel'] },
    { day: 4,  type: 'habit',     task: 'Óleo de coco nas pontas antes de dormir', icon: 'droplets' },
    { day: 5,  type: 'rest',      task: 'Dia de descanso — mantenha a consistência', icon: 'leaf' },
    { day: 6,  type: 'treatment', task: 'Nutrição capilar por 1 hora', icon: 'sparkles', recipe_options: ['oleo-coco-nutricao', 'abacate-coco'] },
    { day: 7,  type: 'checkin',   task: 'Check-in semanal: como está o brilho e a maciez?', icon: 'camera' },
    { day: 8,  type: 'habit',     task: 'Hidratação com babosa pura nos fios', icon: 'droplets' },
    { day: 9,  type: 'treatment', task: 'Hidratação profunda por 20–30 min', icon: 'sparkles', recipe_options: ['babosa-mel', 'mel-azeite'] },
    { day: 10, type: 'habit',     task: 'Evite calor excessivo — prefira secar ao natural', icon: 'droplets' },
    { day: 11, type: 'treatment', task: 'Selagem dos fios após lavagem', icon: 'sparkles', recipe_options: ['vinagre-maca', 'oleo-argan-finalizacao'] },
    { day: 12, type: 'rest',      task: 'Dia de descanso', icon: 'leaf' },
    { day: 13, type: 'habit',     task: 'Massageie o couro cabeludo por 3 minutos', icon: 'droplets' },
    { day: 14, type: 'checkin',   task: 'Check-in de 2 semanas — você está mantendo os resultados?', icon: 'camera' },
    { day: 15, type: 'treatment', task: 'Hidratação profunda por 30–40 min', icon: 'sparkles', recipe_options: ['abacate-azeite', 'banana-mel'] },
    { day: 16, type: 'habit',     task: 'Durma com cabelo solto em travesseiro limpo', icon: 'droplets' },
    { day: 17, type: 'treatment', task: 'Hidratação de manutenção por 20 min', icon: 'sparkles', recipe_options: ['mascara-manutencao', 'babosa-mel'] },
    { day: 18, type: 'rest',      task: 'Dia de descanso', icon: 'leaf' },
    { day: 19, type: 'treatment', task: 'Nutrição capilar por 1 hora', icon: 'sparkles', recipe_options: ['oleo-coco-nutricao', 'mel-azeite'] },
    { day: 20, type: 'habit',     task: 'Aplique mel puro nas pontas por 15 min antes de lavar', icon: 'droplets' },
    { day: 21, type: 'checkin',   task: 'Check-in mensal de manutenção — continue evoluindo! ✨', icon: 'camera' },
  ],
};

// Alias para compatibilidade com código que usa TWENTY_ONE_DAY_PLAN
export const TWENTY_ONE_DAY_PLAN = PHASE_PLANS[1];

export const DAY_TYPE_LABELS = {
  habit: { label: 'Hábito', color: 'text-blue-600', bg: 'bg-blue-50', icon: 'droplets' },
  treatment: { label: 'Tratamento', color: 'text-emerald-600', bg: 'bg-emerald-50', icon: 'sparkles' },
  rest: { label: 'Descanso', color: 'text-stone-500', bg: 'bg-stone-50', icon: 'leaf' },
  checkin: { label: 'Check-in', color: 'text-amber-600', bg: 'bg-amber-50', icon: 'camera' },
};

// Helper: retorna a fase atual baseada nos dias completados
export function getCurrentPhase(completedDays) {
  if (completedDays < 21) return 1;
  if (completedDays < 42) return 2;
  if (completedDays < 63) return 3;
  return 4;
}

// Helper: retorna o plano atual
export function getCurrentPhasePlan(completedDays) {
  const phase = getCurrentPhase(completedDays);
  return { phase, plan: PHASE_PLANS[phase], phaseData: HAIR_PHASES[phase - 1] };
}