export const PRICING_PLANS = {
  monthly: {
    stripe_price_id: import.meta.env.VITE_STRIPE_PRICE_MONTHLY,
    display_price: 6.99,
    interval: 'month',
    period_en: '/month',
    period_es: '/mes',
    label_en: '$6.99/month',
    label_es: '$6.99/mes',
    cta_en: 'Start my plan',
    cta_es: 'Empezar mi plan',
    plan_key: 'monthly_699',
    route_path: '/quiz',
    results_path: '/results',
  },
  monthly_cheap: {
    stripe_price_id: import.meta.env.VITE_STRIPE_PRICE_MONTHLY_CHEAP,
    display_price: 4.99,
    interval: 'month',
    period_en: '/month',
    period_es: '/mes',
    label_en: '$4.99/month',
    label_es: '$4.99/mes',
    cta_en: 'Start my plan',
    cta_es: 'Empezar mi plan',
    plan_key: 'monthly_499',
    route_path: '/quiz-cheap',
    results_path: '/results-cheap',
  },
  monthly_premium: {
    stripe_price_id: import.meta.env.VITE_STRIPE_PRICE_MONTHLY_PREMIUM,
    display_price: 14.99,
    interval: 'month',
    period_en: '/month',
    period_es: '/mes',
    label_en: '$14.99/month',
    label_es: '$14.99/mes',
    cta_en: 'Start my plan',
    cta_es: 'Empezar mi plan',
    plan_key: 'monthly_1499',
    route_path: '/quiz-premium',
    results_path: '/results-premium',
  },
}
