export const PRICING_PLANS = {
  monthly: {
    hotmart_checkout_url: import.meta.env.VITE_HOTMART_CHECKOUT_URL_STANDARD,
    display_price: 27,
    period_label: 'pago único',
    label_es: '$27 USD',
    cta_es: 'Quiero mi plan completo',
    plan_key: 'one_time_standard',
    route_path: '/quiz',
    results_path: '/results',
  },
  monthly_cheap: {
    hotmart_checkout_url: import.meta.env.VITE_HOTMART_CHECKOUT_URL_BASIC,
    display_price: 17,
    period_label: 'pago único',
    label_es: '$17 USD',
    cta_es: 'Quiero empezar ahora',
    plan_key: 'one_time_basic',
    route_path: '/quiz-cheap',
    results_path: '/results-cheap',
  },
  monthly_premium: {
    hotmart_checkout_url: import.meta.env.VITE_HOTMART_CHECKOUT_URL_PREMIUM,
    display_price: 47,
    period_label: 'pago único',
    label_es: '$47 USD',
    cta_es: 'Quiero el plan VIP',
    plan_key: 'one_time_premium',
    route_path: '/quiz-premium',
    results_path: '/results-premium',
  },
  bold: {
    hotmart_checkout_url: import.meta.env.VITE_HOTMART_CHECKOUT_URL_BASIC,
    display_price: 17,
    period_label: 'pago único',
    label_es: '$17 USD',
    cta_es: '¡Sí, lo quiero ya!',
    plan_key: 'one_time_basic',
    route_path: '/quiz-bold',
    results_path: '/results-bold',
  },
}
